FROM node:lts-alpine

# Upgrade system packages to get security patches
RUN apk upgrade --no-cache

WORKDIR /app

COPY *.js ./
COPY package.json ./

RUN npm install && npm audit fix

VOLUME /downloads

CMD ["npm", "start"]